pipeline {
    environment {
        ROOT_DIR='/var/lib/jenkins/workspace/${env.JOB_NAME}'
        PROJECT_NAME='testing-react-with-jest'
        REPOSITORY='https://github.com/IvanAntoff/'
    }
    options {
      timeout(time: 10, unit: 'MINUTES') 
    }
    agent any
    tools {
        nodejs "Node"
    }
    stages {
        stage('Prepare') {
            steps {
                dir(ROOT_DIR) {
                    sh "rm -rf ${PROJECT_NAME}"
                    sh "git clone ${REPOSITORY}${PROJECT_NAME} || true"
                    sh "cd ${PROJECT_NAME} && npm i --force"
                }
            }
        }
        stage('Test') {
            steps {
                dir(ROOT_DIR) {
                    sh "cd ${PROJECT_NAME} && npm run test"
                }
            }
        }
        stage('Build') {
            steps {
                dir(ROOT_DIR) {
                    sh "cd ${PROJECT_NAME} && npm run build"
                }
            }
        }
    }
}