pipeline {
    environment { 
        root_dirname = '/usr/src/app'
        project_name = 'testing-react-with-jest'
    }
    agent any
    stages {
        stage('Prepare') {
            steps {
                dir("/usr/src/app") {
                    sh 'git clone https://github.com/IvanAntoff/testing-react-with-jest || true'
                }
                dir("/usr/src/app/testing-react-with-jest") {
                    sh 'npm i --force'
                }
            }
        }
        // stage('Test') {
        //     steps {
        //         dir(build_dir) {
        //             sh 'npm run test'
        //         }
        //     }
        // }
        // stage('Build') {
        //     steps {
        //         dir(build_dir) {
        //             sh 'npm run start'
        //             sh 'npm run watch'
        //         }
        //     }
        // }
    }
}